import { PrMemoryMapper } from './memory.mapper.js';
import { PrMemoryRecord } from './memory.record.js';
import { PrMemoryEntry } from '../../domain/entities/pr-memory-entry.entity.js';
import { FeedbackOutcome } from '../../domain/value-objects/feedback-outcome.vo.js';

describe('PrMemoryMapper', () => {
  // pgvector serialization stays in the repository, so the mapper takes the
  // already-converted embedding form on each side. These tests pass dummy
  // strings / arrays to verify the wiring contract.
  const sampleEmbedding = [0.1, 0.2, 0.3];
  const sampleEmbeddingSql = '[0.1,0.2,0.3]';

  const buildRecord = (): PrMemoryRecord => {
    const record = new PrMemoryRecord();
    record.id = '11111111-1111-1111-1111-111111111111';
    record.repository_id = '22222222-2222-2222-2222-222222222222';
    record.pr_number = 42;
    record.comment_author = 'reviewer-bot';
    record.comment_text = 'Consider extracting this helper';
    record.code_context = 'function add(a, b) { return a + b }';
    record.outcome = FeedbackOutcome.ACCEPTED;
    record.embedding = sampleEmbeddingSql;
    record.created_at = new Date('2025-01-01T00:00:00.000Z');
    return record;
  };

  it('toDomain reconstitutes domain entity with all fields', () => {
    const record = buildRecord();
    const entry = PrMemoryMapper.toDomain(record, sampleEmbedding);

    expect(entry.id).toBe(record.id);
    expect(entry.repositoryId).toBe(record.repository_id);
    expect(entry.prNumber).toBe(record.pr_number);
    expect(entry.commentAuthor).toBe(record.comment_author);
    expect(entry.commentText).toBe(record.comment_text);
    expect(entry.codeContext).toBe(record.code_context);
    expect(entry.outcome).toBe(record.outcome);
    expect(entry.embedding).toEqual(sampleEmbedding);
  });

  it('toRecord serializes domain entity into record shape with supplied embeddingSql', () => {
    const entry = new PrMemoryEntry({
      id: '33333333-3333-3333-3333-333333333333',
      repositoryId: '44444444-4444-4444-4444-444444444444',
      prNumber: 7,
      commentAuthor: 'human-reviewer',
      commentText: 'Nit: rename for clarity',
      codeContext: 'const x = 1',
      outcome: FeedbackOutcome.DISMISSED,
      embedding: sampleEmbedding,
    });

    const record = PrMemoryMapper.toRecord(entry, sampleEmbeddingSql);

    expect(record).toBeInstanceOf(PrMemoryRecord);
    expect(record.id).toBe(entry.id);
    expect(record.repository_id).toBe(entry.repositoryId);
    expect(record.pr_number).toBe(entry.prNumber);
    expect(record.comment_author).toBe(entry.commentAuthor);
    expect(record.comment_text).toBe(entry.commentText);
    expect(record.code_context).toBe(entry.codeContext);
    expect(record.outcome).toBe(entry.outcome);
    expect(record.embedding).toBe(sampleEmbeddingSql);
    expect(record.created_at).toBe(entry.createdAt);
  });

  it('round-trips record -> domain -> record without losing fields', () => {
    const original = buildRecord();
    const roundTripped = PrMemoryMapper.toRecord(
      PrMemoryMapper.toDomain(original, sampleEmbedding),
      sampleEmbeddingSql,
    );

    // created_at is regenerated by BaseEntity.constructor; exclude it
    const { created_at: _origCreated, ...originalRest } = original;
    const { created_at: _rtCreated, ...roundTrippedRest } = roundTripped;

    expect(roundTrippedRest).toEqual(originalRest);
    expect(roundTripped.created_at).toBeInstanceOf(Date);
  });
});
