import { ReviewMapper } from './review.mapper.js';
import { ReviewRecord } from './review.record.js';
import { Review } from '../../domain/entities/review.entity.js';
import { ReviewStatus } from '../../domain/value-objects/review-status.vo.js';
import { ReviewTrigger } from '../../domain/value-objects/review-trigger.vo.js';

describe('ReviewMapper', () => {
  // Build a fully populated record fixture covering optional metric columns
  const buildRecord = (): ReviewRecord => {
    const record = new ReviewRecord();
    record.id = '11111111-1111-1111-1111-111111111111';
    record.repository_id = '22222222-2222-2222-2222-222222222222';
    record.pr_number = 42;
    record.pr_sha = 'a'.repeat(40);
    record.trigger = ReviewTrigger.AUTO;
    record.status = ReviewStatus.COMPLETED;
    record.raw_diff_lines = 1000;
    record.semantic_diff_lines = 50;
    record.noise_reduction_pct = 95;
    record.model_used = 'claude-sonnet-4-20250514';
    record.prompt_tokens = 3000;
    record.completion_tokens = 500;
    record.review_duration_ms = 12000;
    record.error_message = null;
    record.progress_comment_id = '987654321';
    record.check_run_id = '123456789';
    record.created_at = new Date('2025-01-01T00:00:00.000Z');
    return record;
  };

  it('toDomain reconstitutes domain entity with all fields including optional metrics', () => {
    const record = buildRecord();
    const review = ReviewMapper.toDomain(record);

    expect(review.id).toBe(record.id);
    expect(review.repositoryId).toBe(record.repository_id);
    expect(review.prNumber).toBe(record.pr_number);
    expect(review.prSha).toBe(record.pr_sha);
    expect(review.trigger).toBe(record.trigger);
    expect(review.status).toBe(record.status);
    expect(review.rawDiffLines).toBe(record.raw_diff_lines);
    expect(review.semanticDiffLines).toBe(record.semantic_diff_lines);
    expect(review.noiseReductionPct).toBe(record.noise_reduction_pct);
    expect(review.modelUsed).toBe(record.model_used);
    expect(review.promptTokens).toBe(record.prompt_tokens);
    expect(review.completionTokens).toBe(record.completion_tokens);
    expect(review.reviewDurationMs).toBe(record.review_duration_ms);
    expect(review.errorMessage).toBeUndefined();
  });

  it('toRecord serializes domain entity into record shape', () => {
    const review = Review.create({
      repositoryId: '33333333-3333-3333-3333-333333333333',
      prNumber: 7,
      prSha: 'b'.repeat(40),
      trigger: ReviewTrigger.MANUAL,
    });
    review.markCompleted({
      rawDiffLines: 200,
      semanticDiffLines: 20,
      noiseReductionPct: 90,
      modelUsed: 'gpt-5',
      promptTokens: 1500,
      completionTokens: 250,
      durationMs: 8000,
    });

    const record = ReviewMapper.toRecord(review);

    expect(record).toBeInstanceOf(ReviewRecord);
    expect(record.id).toBe(review.id);
    expect(record.repository_id).toBe(review.repositoryId);
    expect(record.pr_number).toBe(review.prNumber);
    expect(record.pr_sha).toBe(review.prSha);
    expect(record.trigger).toBe(review.trigger);
    expect(record.status).toBe(review.status);
    expect(record.raw_diff_lines).toBe(review.rawDiffLines);
    expect(record.semantic_diff_lines).toBe(review.semanticDiffLines);
    expect(record.noise_reduction_pct).toBe(review.noiseReductionPct);
    expect(record.model_used).toBe(review.modelUsed);
    expect(record.prompt_tokens).toBe(review.promptTokens);
    expect(record.completion_tokens).toBe(review.completionTokens);
    expect(record.review_duration_ms).toBe(review.reviewDurationMs);
    expect(record.error_message).toBeNull();
    expect(record.created_at).toBe(review.createdAt);
  });

  it('round-trips record -> domain -> record without losing fields', () => {
    const original = buildRecord();
    const roundTripped = ReviewMapper.toRecord(ReviewMapper.toDomain(original));

    // created_at is regenerated by BaseEntity.constructor; exclude it
    const { created_at: _origCreated, ...originalRest } = original;
    const { created_at: _rtCreated, ...roundTrippedRest } = roundTripped;

    expect(roundTrippedRest).toEqual(originalRest);
    expect(roundTripped.created_at).toBeInstanceOf(Date);
  });

  it('round-trips a SKIPPED review with only error_message populated', () => {
    const record = new ReviewRecord();
    record.id = '44444444-4444-4444-4444-444444444444';
    record.repository_id = '55555555-5555-5555-5555-555555555555';
    record.pr_number = 99;
    record.pr_sha = 'c'.repeat(40);
    record.trigger = ReviewTrigger.MANUAL;
    record.status = ReviewStatus.SKIPPED;
    record.raw_diff_lines = null;
    record.semantic_diff_lines = null;
    record.noise_reduction_pct = null;
    record.model_used = null;
    record.prompt_tokens = null;
    record.completion_tokens = null;
    record.review_duration_ms = null;
    record.error_message = 'Diff too large';
    record.progress_comment_id = null;
    record.check_run_id = null;
    record.created_at = new Date('2025-02-01T00:00:00.000Z');

    const roundTripped = ReviewMapper.toRecord(ReviewMapper.toDomain(record));

    expect(roundTripped.error_message).toBe('Diff too large');
    expect(roundTripped.raw_diff_lines).toBeNull();
    expect(roundTripped.model_used).toBeNull();
  });
});
